/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eee_Login;

import eee_Main.anasayfaFrame;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Hesty
 */
public class girisFrame extends javax.swing.JFrame {

    /**
     * Creates new form girisFrame
     */
    int xS;
    int yS;

    public girisFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanelÜst.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelÜst = new javax.swing.JPanel();
        jLabelMinimized = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelAlt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sifreText = new javax.swing.JPasswordField();
        kadiText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        girisbtn = new javax.swing.JLabel();
        sifremiunuttumbtn = new javax.swing.JLabel();
        uyeOlLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelÜst.setBackground(new java.awt.Color(243, 156, 18));
        jPanelÜst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelÜst.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelÜstMouseDragged(evt);
            }
        });
        jPanelÜst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelÜstMousePressed(evt);
            }
        });

        jLabelMinimized.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelMinimized.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimized.setText("—");
        jLabelMinimized.setToolTipText("");
        jLabelMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseExited(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setAlignmentY(0.0F);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseReleased(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Elazığ Ev Eşya");

        jPanelAlt.setBackground(new java.awt.Color(75, 75, 75));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/giris.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(75, 75, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kullanıcı Adı:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Şifre:");

        sifreText.setForeground(new java.awt.Color(204, 204, 204));
        sifreText.setText("********");
        sifreText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sifreTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sifreTextFocusLost(evt);
            }
        });
        sifreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreTextActionPerformed(evt);
            }
        });
        sifreText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sifreTextKeyPressed(evt);
            }
        });

        kadiText.setForeground(new java.awt.Color(204, 204, 204));
        kadiText.setText("Kullanıcı Adı Giriniz");
        kadiText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kadiTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kadiTextFocusLost(evt);
            }
        });
        kadiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadiTextActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(75, 75, 75));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        girisbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        girisbtn.setForeground(new java.awt.Color(255, 255, 255));
        girisbtn.setText("Giriş Yap");
        girisbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        girisbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girisbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                girisbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                girisbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(girisbtn)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(girisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sifremiunuttumbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        sifremiunuttumbtn.setForeground(new java.awt.Color(255, 255, 255));
        sifremiunuttumbtn.setText("Şifremi Unuttum");
        sifremiunuttumbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sifremiunuttumbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifremiunuttumbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sifremiunuttumbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sifremiunuttumbtnMouseExited(evt);
            }
        });

        uyeOlLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        uyeOlLabel.setForeground(new java.awt.Color(255, 255, 255));
        uyeOlLabel.setText("Hala üye değilsen Üye OL");
        uyeOlLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uyeOlLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uyeOlLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uyeOlLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uyeOlLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(sifremiunuttumbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(uyeOlLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kadiText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kadiText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifremiunuttumbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(uyeOlLabel)
                .addGap(39, 39, 39))
        );

        kadiText.getAccessibleContext().setAccessibleName("sa");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Giriş Yap");

        javax.swing.GroupLayout jPanelAltLayout = new javax.swing.GroupLayout(jPanelAlt);
        jPanelAlt.setLayout(jPanelAltLayout);
        jPanelAltLayout.setHorizontalGroup(
            jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAltLayout.setVerticalGroup(
            jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelÜstLayout = new javax.swing.GroupLayout(jPanelÜst);
        jPanelÜst.setLayout(jPanelÜstLayout);
        jPanelÜstLayout.setHorizontalGroup(
            jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelÜstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMinimized)
                .addGap(42, 42, 42)
                .addComponent(jLabelClose)
                .addGap(31, 31, 31))
            .addComponent(jPanelAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelÜstLayout.setVerticalGroup(
            jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelÜstLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelÜstLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClose)
                            .addComponent(jLabelMinimized)
                            .addComponent(jLabelTitle)))
                    .addGroup(jPanelÜstLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(7, 7, 7)
                .addComponent(jPanelAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelÜst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelÜst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jLabelClose.setText(":(");
        jLabelClose.setForeground(Color.red);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jLabelClose.setText("X");
        jLabelClose.setForeground(Color.white);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMousePressed

    }//GEN-LAST:event_jLabelCloseMousePressed

    private void jLabelCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseReleased

    }//GEN-LAST:event_jLabelCloseMouseReleased

    private void jLabelMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizedMouseClicked

    private void jLabelMinimizedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseEntered
        jLabelMinimized.setForeground(Color.red);
    }//GEN-LAST:event_jLabelMinimizedMouseEntered

    private void jLabelMinimizedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseExited
        jLabelMinimized.setForeground(Color.white);
    }//GEN-LAST:event_jLabelMinimizedMouseExited

    private void girisbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisbtnMouseEntered
        girisbtn.setForeground(new Color(243, 156, 18));
    }//GEN-LAST:event_girisbtnMouseEntered

    private void girisbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisbtnMouseExited
        girisbtn.setForeground(Color.white);
    }//GEN-LAST:event_girisbtnMouseExited

    private void sifremiunuttumbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifremiunuttumbtnMouseEntered
        sifremiunuttumbtn.setForeground(new Color(243, 156, 18));

    }//GEN-LAST:event_sifremiunuttumbtnMouseEntered

    private void sifremiunuttumbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifremiunuttumbtnMouseExited
        sifremiunuttumbtn.setForeground(Color.white);
    }//GEN-LAST:event_sifremiunuttumbtnMouseExited

    private void uyeOlLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uyeOlLabelMouseEntered
        uyeOlLabel.setForeground(new Color(243, 156, 18));
    }//GEN-LAST:event_uyeOlLabelMouseEntered

    private void uyeOlLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uyeOlLabelMouseExited
        uyeOlLabel.setForeground(Color.white);
    }//GEN-LAST:event_uyeOlLabelMouseExited

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation((x - xS), (y - yS));

    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        xS = evt.getX();
        yS = evt.getY();

    }//GEN-LAST:event_jLabel5MousePressed

    private void kadiTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kadiTextFocusGained

        if (kadiText.getText().equals("Kullanıcı Adı Giriniz")) {
            kadiText.setText("");
        }
        kadiText.setForeground(Color.black);
    }//GEN-LAST:event_kadiTextFocusGained

    private void kadiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kadiTextActionPerformed

    private void kadiTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kadiTextFocusLost

        if (kadiText.getText().equals("")) {
            kadiText.setText("Kullanıcı Adı Giriniz");
            kadiText.setForeground(new Color(204, 204, 204));
        }

    }//GEN-LAST:event_kadiTextFocusLost

    private void sifreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifreTextActionPerformed

    private void sifreTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreTextFocusGained
        if (String.valueOf(sifreText.getPassword()).trim().equals("********")) {

            sifreText.setText("");

        }
        sifreText.setForeground(Color.black);

    }//GEN-LAST:event_sifreTextFocusGained

    private void sifreTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreTextFocusLost

        if (String.valueOf(sifreText.getPassword()).trim().equals("")) {

            sifreText.setText("********");

        }
        setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_sifreTextFocusLost

    private void girisbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisbtnMouseClicked
        PreparedStatement st;
        ResultSet rs;

        String kadi = kadiText.getText();
        String sifre = String.valueOf(sifreText.getPassword());

        String query = "SELECT * FROM `kullanicilar` WHERE `kadi` = ? AND`sifre` = ?";
        try {
            st = mysqL.getConnection().prepareStatement(query);

            st.setString(1, kadi);
            st.setString(2, sifre);
            rs = st.executeQuery();

            if (rs.next()) {
                
                anasayfaFrame form = new anasayfaFrame();
                 anasayfaFrame.gizle(anasayfaFrame.ev);
                 anasayfaFrame.kadiHesap.setText(kadi);
                 anasayfaFrame.sifreHesap.setText(sifre);
                form.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Kullanıcı adı veya Şifre Hatalı", "Giriş Hatası", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(girisFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_girisbtnMouseClicked

    private void uyeOlLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uyeOlLabelMouseClicked
        kayitOlFrame frm = new kayitOlFrame();
        frm.setVisible(true);
        frm.pack();
        this.dispose();
    }//GEN-LAST:event_uyeOlLabelMouseClicked

    private void sifreTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifreTextKeyPressed

    }//GEN-LAST:event_sifreTextKeyPressed

    private void sifremiunuttumbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifremiunuttumbtnMouseClicked
        sifremiUnuttum frm = new sifremiUnuttum();
        frm.setVisible(true);
        frm.pack();
        this.dispose();

    }//GEN-LAST:event_sifremiunuttumbtnMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanelÜstMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelÜstMouseDragged

    }//GEN-LAST:event_jPanelÜstMouseDragged

    private void jPanelÜstMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelÜstMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelÜstMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisFrame().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel girisbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimized;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAlt;
    private javax.swing.JPanel jPanelÜst;
    private javax.swing.JTextField kadiText;
    private javax.swing.JPasswordField sifreText;
    private javax.swing.JLabel sifremiunuttumbtn;
    private javax.swing.JLabel uyeOlLabel;
    // End of variables declaration//GEN-END:variables
}
