/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eee_Login;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hesty
 */
public class kayitOlFrame extends javax.swing.JFrame {

    /**
     * Creates new form kayitOlFrame
     */
    int xS;
    int yS;

    public kayitOlFrame() {
        initComponents();

        this.setLocationRelativeTo(null);
        jPanelÜst.setFocusable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelÜst = new javax.swing.JPanel();
        jLabelMinimized = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelAlt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ilce = new javax.swing.JComboBox<>();
        il = new javax.swing.JComboBox<>();
        kayitOl = new javax.swing.JLabel();
        girisbtn = new javax.swing.JLabel();
        adresText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        eposta = new javax.swing.JTextField();
        adi = new javax.swing.JTextField();
        soyadi = new javax.swing.JTextField();
        kadi = new javax.swing.JTextField();
        telefonNo = new javax.swing.JTextField();
        sfre = new javax.swing.JPasswordField();
        sfre2 = new javax.swing.JPasswordField();
        dgmtarihi = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(75, 75, 75));
        setUndecorated(true);

        jPanelÜst.setBackground(new java.awt.Color(243, 156, 18));
        jPanelÜst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMinimized.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelMinimized.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimized.setText("—");
        jLabelMinimized.setToolTipText("");
        jLabelMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseExited(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setAlignmentY(0.0F);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseReleased(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Elazığ Ev Eşya");

        jPanelAlt.setBackground(new java.awt.Color(75, 75, 75));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resimler/giris.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(75, 75, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kullanıcı Adı:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Şifre:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adınız:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Doğum Tarihi:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-Posta Adresi:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("İl:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Soyadınız:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("İlçe:");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Adres:");

        ilce.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ilce.setForeground(new java.awt.Color(255, 255, 255));
        ilce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ağın", "Alacakaya", "Arıcak", "Baskil", "Karakoçan", "Keban", "Kovancılar", "Maden", "Merkez", "Palu", "Sivrice" }));
        ilce.setToolTipText("");

        il.setForeground(new java.awt.Color(255, 255, 255));
        il.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elazığ" }));

        kayitOl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        kayitOl.setForeground(new java.awt.Color(255, 255, 255));
        kayitOl.setText("Kayıt OL");
        kayitOl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kayitOl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayitOlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kayitOlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kayitOlMouseExited(evt);
            }
        });

        girisbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        girisbtn.setForeground(new java.awt.Color(255, 255, 255));
        girisbtn.setText("Giriş Yap");
        girisbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        girisbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girisbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                girisbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                girisbtnMouseExited(evt);
            }
        });

        adresText.setBackground(new java.awt.Color(75, 75, 75));
        adresText.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Şifre Tekrarı:");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefon Numaranız:");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("+90");

        eposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epostaActionPerformed(evt);
            }
        });

        adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiActionPerformed(evt);
            }
        });

        soyadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyadiActionPerformed(evt);
            }
        });

        kadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadiActionPerformed(evt);
            }
        });

        telefonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonNoActionPerformed(evt);
            }
        });
        telefonNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonNoKeyTyped(evt);
            }
        });

        sfre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfreActionPerformed(evt);
            }
        });

        sfre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfre2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kadi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefonNo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addComponent(eposta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soyadi)
                            .addComponent(sfre)
                            .addComponent(sfre2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(160, 160, 160))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dgmtarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(girisbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kayitOl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adresText, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ilce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(il, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(eposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(telefonNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sfre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sfre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dgmtarihi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(il, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ilce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adresText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kayıt OL");

        javax.swing.GroupLayout jPanelAltLayout = new javax.swing.GroupLayout(jPanelAlt);
        jPanelAlt.setLayout(jPanelAltLayout);
        jPanelAltLayout.setHorizontalGroup(
            jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelAltLayout.setVerticalGroup(
            jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(jPanelAltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAltLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAltLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelÜstLayout = new javax.swing.GroupLayout(jPanelÜst);
        jPanelÜst.setLayout(jPanelÜstLayout);
        jPanelÜstLayout.setHorizontalGroup(
            jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelÜstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMinimized)
                .addGap(42, 42, 42)
                .addComponent(jLabelClose)
                .addGap(31, 31, 31))
            .addComponent(jPanelAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelÜstLayout.setVerticalGroup(
            jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelÜstLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelÜstLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelÜstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClose)
                            .addComponent(jLabelMinimized)
                            .addComponent(jLabelTitle)))
                    .addGroup(jPanelÜstLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(7, 7, 7)
                .addComponent(jPanelAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelÜst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelÜst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizedMouseClicked

    private void jLabelMinimizedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseEntered
        jLabelMinimized.setForeground(Color.red);
    }//GEN-LAST:event_jLabelMinimizedMouseEntered

    private void jLabelMinimizedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseExited
        jLabelMinimized.setForeground(Color.white);
    }//GEN-LAST:event_jLabelMinimizedMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jLabelClose.setText(":(");
        jLabelClose.setForeground(Color.red);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jLabelClose.setText("X");
        jLabelClose.setForeground(Color.white);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMousePressed

    }//GEN-LAST:event_jLabelCloseMousePressed

    private void jLabelCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseReleased

    }//GEN-LAST:event_jLabelCloseMouseReleased

    private void girisbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisbtnMouseEntered
        girisbtn.setForeground(new Color(243, 156, 18));
    }//GEN-LAST:event_girisbtnMouseEntered

    private void girisbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisbtnMouseExited
        girisbtn.setForeground(Color.white);
    }//GEN-LAST:event_girisbtnMouseExited

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation((x - xS), (y - yS));
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        xS = evt.getX();
        yS = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void kayitOlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitOlMouseEntered
        kayitOl.setForeground(new Color(243, 156, 18));
    }//GEN-LAST:event_kayitOlMouseEntered

    private void kayitOlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitOlMouseExited
        kayitOl.setForeground(Color.WHITE);
    }//GEN-LAST:event_kayitOlMouseExited

    private void girisbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisbtnMouseClicked
        girisFrame frm = new girisFrame();
        frm.setVisible(true);
        frm.pack();
        this.dispose();
    }//GEN-LAST:event_girisbtnMouseClicked

    private void epostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epostaActionPerformed

    private void adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adiActionPerformed

    private void soyadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyadiActionPerformed

    private void kadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kadiActionPerformed

    private void telefonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonNoActionPerformed

    private void telefonNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonNoKeyTyped

        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_telefonNoKeyTyped

    private void kayitOlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitOlMouseClicked
        String kuadi = kadi.getText();
        String isim = adi.getText();
        String soyd = soyadi.getText();
        String epst = eposta.getText();
        String cep = telefonNo.getText();
        String sfre1 = String.valueOf(sfre.getPassword());
        String sfree2 = String.valueOf(sfre2.getPassword());
        String dgm = dgmtarihi.getText();
        String ill = il.getSelectedItem().toString();
        String ilcee = ilce.getSelectedItem().toString();
        String adrs = adresText.getText();

        if (girisleriDogrula()) {
            if (!kadiBak(kuadi)) {
                if (!epostaBak(epst)) {
                    PreparedStatement ps;
                    ResultSet re;
                    String kullaniciKayitQery = "INSERT INTO `kullanicilar`(`kadi`, `adi`, `soyadi`, `eposta`, `telefonno`, `sifre`, `dgmtarihi`,`il`,`ilce`, `adres`) VALUES (?,?,?,?,?,?,?,?,?,?)";

                    try {
                        ps = mysqL.getConnection().prepareStatement(kullaniciKayitQery);

                        ps.setString(1, kuadi);
                        ps.setString(2, isim);
                        ps.setString(3, soyd);
                        ps.setString(4, epst);
                        ps.setString(5, cep);
                        ps.setString(6, sfre1);
                        ps.setString(7, dgm);
                        ps.setString(8, ill);
                        ps.setString(9, ilcee);
                        ps.setString(10, adrs);

                        try {
                            if (ps.executeUpdate() != 0) {

                                JOptionPane.showMessageDialog(null, "Hesabınız oluşturuldu");
                            } else {
                                JOptionPane.showMessageDialog(null, "Hata: Bilgilerinizi Kontrol Edin!");
                            }

                        } catch (SQLException ex) {
                            Logger.getLogger(kayitOlFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(kayitOlFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

        }

    }//GEN-LAST:event_kayitOlMouseClicked

    private void sfreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfreActionPerformed

    private void sfre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfre2ActionPerformed
//bilgilerin eksiksiz olduğu kontrol ettim

    public boolean girisleriDogrula() {
        String kuadi = kadi.getText();
        String isim = adi.getText();
        String soyd = soyadi.getText();
        String epst = eposta.getText();
        String cep = telefonNo.getText();
        String sfre1 = String.valueOf(sfre.getPassword());
        String sfree2 = String.valueOf(sfre2.getPassword());
        String dgm = dgmtarihi.getText();
        String ill = il.getSelectedItem().toString();
        String ilcee = ilce.getSelectedItem().toString();
        String adrs = adresText.getText();

        if (kuadi.trim().equals("") || isim.trim().equals("") || soyd.trim().equals("")
                || epst.trim().equals("") || cep.trim().equals("") || sfre1.trim().equals("")
                || sfree2.trim().equals("") || dgm.trim().equals("") || ill.trim().equals("") || ilcee.trim().equals("") || adrs.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lütfen Bilgilerinizi Kontrol Edin!", "Boş Geçmeyiniz!", 2);
            return false;
        } else if (!sfre1.equals(sfree2)) {
            JOptionPane.showMessageDialog(null, "Şifreleriniz Uyuşmuyor!", "Lütfen Kontrol Edin!", 2);
            return false;
        } else {

            return true;
        }
    }
//kullanıcı adının benzersiz olup olmadığını kontrol ettim

    public boolean kadiBak(String kuadi) {
        PreparedStatement st;
        ResultSet rs;
        boolean kuadi_exit = false;

        String guery = "SELECT * FROM `kullanicilar` WHERE `kadi` = ?";

        try {
            st = mysqL.getConnection().prepareStatement(guery);
            st.setString(1, kuadi);
            rs = st.executeQuery();

            if (rs.next()) {
                kuadi_exit = true;
                JOptionPane.showMessageDialog(null, "Bu kullanıcı önceden kayıtlı", "Farklı bir kullanıcı ismi deneyin", 2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(kayitOlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return kuadi_exit;
    }
//postanın benzersiz olduguna bakıldı

    public boolean epostaBak(String eposta) {
        PreparedStatement st;
        ResultSet rs;
        boolean eposta_exit = false;

        String guery = "SELECT * FROM `kullanicilar` WHERE `eposta` = ?";

        try {
            st = mysqL.getConnection().prepareStatement(guery);
            st.setString(1, eposta);
            rs = st.executeQuery();

            if (rs.next()) {
                eposta_exit = true;
                JOptionPane.showMessageDialog(null, "Farklı bir e-posta adresi deneyin", "Kayıtlı E-Posta", 2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(kayitOlFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return eposta_exit;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitOlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new kayitOlFrame().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adi;
    private javax.swing.JTextField adresText;
    private datechooser.beans.DateChooserCombo dgmtarihi;
    private javax.swing.JTextField eposta;
    private javax.swing.JLabel girisbtn;
    private javax.swing.JComboBox<String> il;
    private javax.swing.JComboBox<String> ilce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimized;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAlt;
    private javax.swing.JPanel jPanelÜst;
    private javax.swing.JTextField kadi;
    private javax.swing.JLabel kayitOl;
    private javax.swing.JPasswordField sfre;
    private javax.swing.JPasswordField sfre2;
    private javax.swing.JTextField soyadi;
    private javax.swing.JTextField telefonNo;
    // End of variables declaration//GEN-END:variables
}
