/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eee_Main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Cihat
 */
public class esyaDetay extends javax.swing.JFrame {

    /**
     * Creates new form evDetay
     */
    public esyaDetay() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ustPanel = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMinimized = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        resimEsya = new javax.swing.JLabel();
        baslikEsya = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        baslik6 = new javax.swing.JLabel();
        baslik9 = new javax.swing.JLabel();
        baslik10 = new javax.swing.JLabel();
        baslik11 = new javax.swing.JLabel();
        baslik12 = new javax.swing.JLabel();
        baslik13 = new javax.swing.JLabel();
        baslik18 = new javax.swing.JLabel();
        baslik33 = new javax.swing.JLabel();
        baslik14 = new javax.swing.JLabel();
        garantiEsya = new javax.swing.JLabel();
        fiyatEsya = new javax.swing.JLabel();
        kategori = new javax.swing.JLabel();
        modelEsya = new javax.swing.JLabel();
        markaEsya = new javax.swing.JLabel();
        telefonEsya = new javax.swing.JLabel();
        takasEsya = new javax.swing.JLabel();
        ilanshbEsya = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        baslik21 = new javax.swing.JLabel();
        baslik25 = new javax.swing.JLabel();
        ilce = new javax.swing.JLabel();
        baslik27 = new javax.swing.JLabel();
        baslik28 = new javax.swing.JLabel();
        mahalle = new javax.swing.JLabel();
        acikAdresEsya = new javax.swing.JLabel();
        telefonEsya1 = new javax.swing.JLabel();
        ilEsya = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mahalleEsya = new javax.swing.JLabel();
        ilceEsya = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ulasim = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aciklama = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        teknik2 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ustPanel.setBackground(new java.awt.Color(243, 156, 18));

        jLabelClose.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setAlignmentY(0.0F);
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });

        jLabelMinimized.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelMinimized.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimized.setText("—");
        jLabelMinimized.setToolTipText("");
        jLabelMinimized.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseExited(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Eşya Detay");

        javax.swing.GroupLayout ustPanelLayout = new javax.swing.GroupLayout(ustPanel);
        ustPanel.setLayout(ustPanelLayout);
        ustPanelLayout.setHorizontalGroup(
            ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ustPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimized)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        ustPanelLayout.setVerticalGroup(
            ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ustPanelLayout.createSequentialGroup()
                .addGroup(ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ustPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMinimized)
                            .addComponent(jLabelClose)))
                    .addComponent(jLabelTitle))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 156, 18), 5));

        resimEsya.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        baslikEsya.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        baslikEsya.setForeground(new java.awt.Color(255, 255, 255));
        baslikEsya.setText("İlan Başlığı");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        baslik6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik6.setForeground(new java.awt.Color(255, 255, 255));
        baslik6.setText("Fiyat:");

        baslik9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik9.setForeground(new java.awt.Color(255, 255, 255));
        baslik9.setText("Kategori:");

        baslik10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik10.setForeground(new java.awt.Color(255, 255, 255));
        baslik10.setText("Model:");

        baslik11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik11.setForeground(new java.awt.Color(255, 255, 255));
        baslik11.setText("Takaslı:");

        baslik12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik12.setForeground(new java.awt.Color(255, 255, 255));
        baslik12.setText("İlan Sahibi:");

        baslik13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik13.setForeground(new java.awt.Color(255, 255, 255));
        baslik13.setText("Telefon:");

        baslik18.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik18.setForeground(new java.awt.Color(255, 255, 255));
        baslik18.setText("TL");

        baslik33.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik33.setForeground(new java.awt.Color(255, 255, 255));
        baslik33.setText("Marka:");

        baslik14.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik14.setForeground(new java.awt.Color(255, 255, 255));
        baslik14.setText("Garanti:");

        garantiEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        garantiEsya.setForeground(new java.awt.Color(255, 255, 255));

        fiyatEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        fiyatEsya.setForeground(new java.awt.Color(255, 255, 255));

        kategori.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        kategori.setForeground(new java.awt.Color(255, 255, 255));

        modelEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        modelEsya.setForeground(new java.awt.Color(255, 255, 255));

        markaEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        markaEsya.setForeground(new java.awt.Color(255, 255, 255));

        telefonEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        telefonEsya.setForeground(new java.awt.Color(255, 255, 255));

        takasEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        takasEsya.setForeground(new java.awt.Color(255, 255, 255));

        ilanshbEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ilanshbEsya.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(baslik6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiyatEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(baslik18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(baslik11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takasEsya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(baslik9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(baslik33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(markaEsya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(baslik12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ilanshbEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(baslik13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telefonEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(baslik14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(garantiEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(baslik10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modelEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(baslik18, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(baslik6))
                    .addComponent(fiyatEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baslik9)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baslik33)
                    .addComponent(markaEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baslik10)
                    .addComponent(modelEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baslik14)
                    .addComponent(garantiEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baslik11)
                    .addComponent(takasEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(baslik12)
                    .addComponent(ilanshbEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baslik13)
                    .addComponent(telefonEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        baslik21.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik21.setForeground(new java.awt.Color(255, 255, 255));
        baslik21.setText("İl:");

        baslik25.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik25.setForeground(new java.awt.Color(255, 255, 255));
        baslik25.setText("İlçe:");

        ilce.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ilce.setForeground(new java.awt.Color(255, 255, 255));

        baslik27.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik27.setForeground(new java.awt.Color(255, 255, 255));
        baslik27.setText("Mahalle:");

        baslik28.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik28.setForeground(new java.awt.Color(255, 255, 255));
        baslik28.setText("Adres:");

        mahalle.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        mahalle.setForeground(new java.awt.Color(255, 255, 255));

        acikAdresEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        acikAdresEsya.setForeground(new java.awt.Color(255, 255, 255));

        telefonEsya1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        ilEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ilEsya.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        mahalleEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        mahalleEsya.setForeground(new java.awt.Color(255, 255, 255));

        ilceEsya.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ilceEsya.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telefonEsya1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(baslik21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ilEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(baslik25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(ilce, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ilceEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(baslik27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(mahalle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mahalleEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(baslik28)
                        .addGap(43, 43, 43)
                        .addComponent(acikAdresEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(telefonEsya1)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ilEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baslik21))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(baslik25)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ilce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ilceEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(baslik27)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mahalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mahalleEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baslik28)
                    .addComponent(acikAdresEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ulasim.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ulasim.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(ulasim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 630, 30));

        aciklama.setEditable(false);
        aciklama.setBackground(new java.awt.Color(204, 204, 204));
        aciklama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Açıklama", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        aciklama.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        aciklama.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(aciklama);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 310, 360));

        teknik2.setEditable(false);
        teknik2.setBackground(new java.awt.Color(204, 204, 204));
        teknik2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teknik Özellikler", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        teknik2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        teknik2.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(teknik2);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 470, 360));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(baslikEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resimEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baslikEsya)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(resimEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ustPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ustPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseExited
        jLabelMinimized.setForeground(Color.white);
    }//GEN-LAST:event_jLabelMinimizedMouseExited

    private void jLabelMinimizedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseEntered
        jLabelMinimized.setForeground(Color.red);
    }//GEN-LAST:event_jLabelMinimizedMouseEntered

    private void jLabelMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizedMouseClicked

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jLabelClose.setForeground(Color.white);
        jLabelClose.setText("X");
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jLabelClose.setForeground(Color.red);
        jLabelClose.setText(":(");
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(esyaDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(esyaDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(esyaDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(esyaDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new esyaDetay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel acikAdresEsya;
    public javax.swing.JEditorPane aciklama;
    private javax.swing.JLabel baslik10;
    private javax.swing.JLabel baslik11;
    private javax.swing.JLabel baslik12;
    private javax.swing.JLabel baslik13;
    private javax.swing.JLabel baslik14;
    private javax.swing.JLabel baslik18;
    private javax.swing.JLabel baslik21;
    private javax.swing.JLabel baslik25;
    private javax.swing.JLabel baslik27;
    private javax.swing.JLabel baslik28;
    private javax.swing.JLabel baslik33;
    private javax.swing.JLabel baslik6;
    private javax.swing.JLabel baslik9;
    public javax.swing.JLabel baslikEsya;
    public javax.swing.JLabel fiyatEsya;
    public javax.swing.JLabel garantiEsya;
    public javax.swing.JLabel ilEsya;
    public javax.swing.JLabel ilanshbEsya;
    public static javax.swing.JLabel ilce;
    public javax.swing.JLabel ilceEsya;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimized;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel kategori;
    public static javax.swing.JLabel mahalle;
    public javax.swing.JLabel mahalleEsya;
    public javax.swing.JLabel markaEsya;
    public javax.swing.JLabel modelEsya;
    public javax.swing.JLabel resimEsya;
    public javax.swing.JLabel takasEsya;
    public javax.swing.JEditorPane teknik2;
    public javax.swing.JLabel telefonEsya;
    public static javax.swing.JLabel telefonEsya1;
    public static javax.swing.JLabel ulasim;
    private javax.swing.JPanel ustPanel;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resimler/1111.png")));
    }
}
