/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eee_Main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Cihat
 */
public class evDetay extends javax.swing.JFrame {

    /**
     * Creates new form evDetay
     */
    public evDetay() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ustPanel = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMinimized = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        baslik = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        binaYasi = new javax.swing.JLabel();
        baslik5 = new javax.swing.JLabel();
        baslik6 = new javax.swing.JLabel();
        fiyat = new javax.swing.JLabel();
        baslik8 = new javax.swing.JLabel();
        baslik9 = new javax.swing.JLabel();
        baslik10 = new javax.swing.JLabel();
        baslik11 = new javax.swing.JLabel();
        baslik12 = new javax.swing.JLabel();
        baslik13 = new javax.swing.JLabel();
        telefon = new javax.swing.JLabel();
        aidat = new javax.swing.JLabel();
        balkon = new javax.swing.JLabel();
        baslik18 = new javax.swing.JLabel();
        cephe = new javax.swing.JLabel();
        ilanSahibi = new javax.swing.JLabel();
        baslik15 = new javax.swing.JLabel();
        odaSayisi = new javax.swing.JLabel();
        metrekare = new javax.swing.JLabel();
        baslik33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        baslik21 = new javax.swing.JLabel();
        il = new javax.swing.JLabel();
        baslik25 = new javax.swing.JLabel();
        ilce = new javax.swing.JLabel();
        baslik27 = new javax.swing.JLabel();
        baslik28 = new javax.swing.JLabel();
        mahalle = new javax.swing.JLabel();
        acikAdres = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        baslik23 = new javax.swing.JLabel();
        baslik24 = new javax.swing.JLabel();
        disOzellikler = new javax.swing.JLabel();
        icOzellikler = new javax.swing.JLabel();
        baslik36 = new javax.swing.JLabel();
        ulasim = new javax.swing.JLabel();
        baslik38 = new javax.swing.JLabel();
        kullanimDurumu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ustPanel.setBackground(new java.awt.Color(243, 156, 18));

        jLabelClose.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setAlignmentY(0.0F);
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });

        jLabelMinimized.setFont(new java.awt.Font("Arial Narrow", 0, 21)); // NOI18N
        jLabelMinimized.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimized.setText("—");
        jLabelMinimized.setToolTipText("");
        jLabelMinimized.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizedMouseExited(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Ev Detay");

        javax.swing.GroupLayout ustPanelLayout = new javax.swing.GroupLayout(ustPanel);
        ustPanel.setLayout(ustPanelLayout);
        ustPanelLayout.setHorizontalGroup(
            ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ustPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimized)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        ustPanelLayout.setVerticalGroup(
            ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ustPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinimized)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelTitle))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 156, 18), 5));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        baslik.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        baslik.setForeground(new java.awt.Color(255, 255, 255));
        baslik.setText("İlan Başlığı");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        binaYasi.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        binaYasi.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(binaYasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 150, 120, -1));

        baslik5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik5.setForeground(new java.awt.Color(255, 255, 255));
        baslik5.setText("TL");
        jPanel2.add(baslik5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        baslik6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik6.setForeground(new java.awt.Color(255, 255, 255));
        baslik6.setText("Fiyat:");
        jPanel2.add(baslik6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, -1, -1));

        fiyat.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        fiyat.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 40, 85, -1));

        baslik8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik8.setForeground(new java.awt.Color(255, 255, 255));
        baslik8.setText("Aidat:");
        jPanel2.add(baslik8, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 70, -1, -1));

        baslik9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik9.setForeground(new java.awt.Color(255, 255, 255));
        baslik9.setText("Balkon:");
        jPanel2.add(baslik9, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 100, -1, -1));

        baslik10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik10.setForeground(new java.awt.Color(255, 255, 255));
        baslik10.setText("Bina Yaşı:");
        jPanel2.add(baslik10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 150, -1, -1));

        baslik11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik11.setForeground(new java.awt.Color(255, 255, 255));
        baslik11.setText("Bulunduğu Cephe:");
        jPanel2.add(baslik11, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 200, -1, -1));

        baslik12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik12.setForeground(new java.awt.Color(255, 255, 255));
        baslik12.setText("İlan Sahibi:");
        jPanel2.add(baslik12, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 250, -1, -1));

        baslik13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik13.setForeground(new java.awt.Color(255, 255, 255));
        baslik13.setText("Telefon:");
        jPanel2.add(baslik13, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 290, -1, -1));

        telefon.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        telefon.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(telefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 240, -1));

        aidat.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        aidat.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(aidat, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 70, 85, -1));

        balkon.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        balkon.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(balkon, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 100, 240, -1));

        baslik18.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik18.setForeground(new java.awt.Color(255, 255, 255));
        baslik18.setText("TL");
        jPanel2.add(baslik18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        cephe.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        cephe.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(cephe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 201, 180, -1));

        ilanSahibi.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ilanSahibi.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ilanSahibi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 250, -1));

        baslik15.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik15.setForeground(new java.awt.Color(255, 255, 255));
        baslik15.setText("Oda Sayısı:");
        jPanel2.add(baslik15, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 176, -1, -1));

        odaSayisi.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        odaSayisi.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(odaSayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 176, 170, -1));

        metrekare.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        metrekare.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(metrekare, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 126, 210, -1));

        baslik33.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik33.setForeground(new java.awt.Color(255, 255, 255));
        baslik33.setText("m^2");
        jPanel2.add(baslik33, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 126, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baslik21.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik21.setForeground(new java.awt.Color(255, 255, 255));
        baslik21.setText("İl:");
        jPanel3.add(baslik21, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, -1));

        il.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        il.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(il, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 14, 250, -1));

        baslik25.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik25.setForeground(new java.awt.Color(255, 255, 255));
        baslik25.setText("İlçe:");
        jPanel3.add(baslik25, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, -1, -1));

        ilce.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ilce.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(ilce, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 40, 250, -1));

        baslik27.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik27.setForeground(new java.awt.Color(255, 255, 255));
        baslik27.setText("Mahalle:");
        jPanel3.add(baslik27, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 70, -1, -1));

        baslik28.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik28.setForeground(new java.awt.Color(255, 255, 255));
        baslik28.setText("Adres:");
        jPanel3.add(baslik28, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 110, -1, -1));

        mahalle.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        mahalle.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(mahalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 70, 250, -1));

        acikAdres.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        acikAdres.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(acikAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 110, 250, 340));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baslik23.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik23.setForeground(new java.awt.Color(255, 255, 255));
        baslik23.setText("İç Özellikler:");
        jPanel4.add(baslik23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        baslik24.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik24.setForeground(new java.awt.Color(255, 255, 255));
        baslik24.setText("Dış Özellikler:");
        jPanel4.add(baslik24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        disOzellikler.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        disOzellikler.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(disOzellikler, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 700, 110));

        icOzellikler.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        icOzellikler.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(icOzellikler, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 700, 110));

        baslik36.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik36.setForeground(new java.awt.Color(255, 255, 255));
        baslik36.setText("Ulaşım:");
        jPanel4.add(baslik36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        ulasim.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ulasim.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(ulasim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 630, 30));

        baslik38.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        baslik38.setForeground(new java.awt.Color(255, 255, 255));
        baslik38.setText("Kullanım Durumu:");
        jPanel4.add(baslik38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        kullanimDurumu.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        kullanimDurumu.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(kullanimDurumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 620, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(baslik, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baslik)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ustPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ustPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimizedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseExited
        jLabelMinimized.setForeground(Color.white);
    }//GEN-LAST:event_jLabelMinimizedMouseExited

    private void jLabelMinimizedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseEntered
        jLabelMinimized.setForeground(Color.red);
    }//GEN-LAST:event_jLabelMinimizedMouseEntered

    private void jLabelMinimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizedMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizedMouseClicked

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jLabelClose.setForeground(Color.white);
        jLabelClose.setText("X");
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jLabelClose.setForeground(Color.red);
        jLabelClose.setText(":(");
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(evDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(evDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(evDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(evDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new evDetay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acikAdres;
    public static javax.swing.JLabel aidat;
    public static javax.swing.JLabel balkon;
    public static javax.swing.JLabel baslik;
    private javax.swing.JLabel baslik10;
    private javax.swing.JLabel baslik11;
    private javax.swing.JLabel baslik12;
    private javax.swing.JLabel baslik13;
    private javax.swing.JLabel baslik15;
    private javax.swing.JLabel baslik18;
    private javax.swing.JLabel baslik21;
    private javax.swing.JLabel baslik23;
    private javax.swing.JLabel baslik24;
    private javax.swing.JLabel baslik25;
    private javax.swing.JLabel baslik27;
    private javax.swing.JLabel baslik28;
    private javax.swing.JLabel baslik33;
    private javax.swing.JLabel baslik36;
    private javax.swing.JLabel baslik38;
    private javax.swing.JLabel baslik5;
    private javax.swing.JLabel baslik6;
    private javax.swing.JLabel baslik8;
    private javax.swing.JLabel baslik9;
    public static javax.swing.JLabel binaYasi;
    public static javax.swing.JLabel cephe;
    public static javax.swing.JLabel disOzellikler;
    public static javax.swing.JLabel fiyat;
    public static javax.swing.JLabel icOzellikler;
    public static javax.swing.JLabel il;
    public static javax.swing.JLabel ilanSahibi;
    public static javax.swing.JLabel ilce;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinimized;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel kullanimDurumu;
    public static javax.swing.JLabel mahalle;
    public static javax.swing.JLabel metrekare;
    public static javax.swing.JLabel odaSayisi;
    public static javax.swing.JLabel telefon;
    public static javax.swing.JLabel ulasim;
    private javax.swing.JPanel ustPanel;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resimler/1111.png")));
    }
}
